apiVersion: v1
kind: Pod
metadata:
  name: init-example
spec:
  initContainers:
  - name: my-initializer
    image: app-initializer
  containers:
  - name: main-container
    image: godchiken/eks-spring-boot:cat-server
  - name: last-container
    image: godchiken/eks-spring-boot:dog-server