# 클러스터 외부에도 접근이 가능한 방식으로 모든 노드의 특정 포트를 개방하여 서비스에 접근하는 방식
# kubectl get services
  #  NAME                    TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE     SELECTOR
  #  hostname-svc-nodeport   NodePort    10.96.65.95   <none>        8080:32267/TCP   31s     app=webserver
# curl 10.96.65.95:32267 --silent | grep Hello
# AWS 보안그룹에 inbound 규칙을 추가해야 올바르게 동작한다.
# clusterip의 기능을 가지고 있기때문에 내,외부 네트워크 양쪽을 통해서 접속이 가능하다.
# nodePort는 80, 443로 포트를 설정하기 적절하지 않고 SSL, Routing설정에 적합하지 않다.

apiVersion: v1
kind: Service
metadata:
  name: hostname-svc-nodeport
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: web-port
  selector:
    app: webserver
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: my-webserver
      labels:
        app: webserver
    spec:
      containers:
        - name: my-webserver
          image: alicek106/rr-test:echo-hostname
          ports:
            - containerPort: 80