# 설치
# helm upgrade --install ingress-nginx ingress-nginx \
# --repo https://kubernetes.github.io/ingress-nginx \
# --namespace ingress-nginx --create-namespace

#  helm upgrade --install ingress-nginx ingress-nginx \
#   --repo https://kubernetes.github.io/ingress-nginx \
#   --namespace pet --create-namespace

# 실행
# helm show values ingress-nginx --repo https://kubernetes.github.io/ingress-nginx

# kubectl -n ingress-nginx get pod -o yaml

# apiVersion: networking.k8s.io/v1      # v1.20 이전

#  kubectl delete -f pet-server.yml
#  kubectl apply -f pet-server.yml
#  kubectl get all -n pet


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pet-ingress
  namespace: ingress-nginx
  annotations:
    spec.ingressClassName: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
     - http:
        paths:
          - path: /cat
            pathType: Prefix
            backend:
              service:
                name: my-cat-svc
                port:
                  number: 8080
          - path: /dog
            pathType: Prefix
            backend:
              service:
                name: my-dog-svc
                port:
                  number: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: ingress-nginx
  name: my-cat-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: my-cat-server
    type: backend
    available: "true"
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: ingress-nginx
  name: my-dog-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: my-dog-server
    type: backend
    available: "true"
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ingress-nginx
  name: cat-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-cat-server
      type: backend
      available: "true"
  template:
    metadata:
      labels:
        app: my-cat-server
        type: backend
        available: "true"
    spec:
      containers:
        - name: my-cat-server
          image: pet-server:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ingress-nginx
  name: dog-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-dog-server
      type: backend
      available: "true"
  template:
    metadata:
      labels:
        app: my-dog-server
        type: backend
        available: "true"
    spec:
      containers:
        - name: my-dog-server
          image: pet-server:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
